//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TowzinSaravan.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int Id { get; set; }
        public int InvoiceTypeId { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<int> OrderId { get; set; }
        public int ProductTypeId { get; set; }
        public string CarDigit1 { get; set; }
        public string CarLetter { get; set; }
        public string CarDigit2 { get; set; }
        public string CarDigit3 { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> SourceFullWeight { get; set; }
        public Nullable<int> SourceEmptyWeight { get; set; }
        public Nullable<int> SourceNetWeight { get; set; }
        public int FullWeight { get; set; }
        public int EmptyWeight { get; set; }
        public int NetWeight { get; set; }
        public bool FirstScale { get; set; }
        public System.DateTime FirstScaleDate { get; set; }
        public System.TimeSpan FirstScaleTime { get; set; }
        public int UserIdForFirstScale { get; set; }
        public bool SecondScale { get; set; }
        public Nullable<System.DateTime> SecondScaleDate { get; set; }
        public Nullable<System.TimeSpan> SecondScaleTime { get; set; }
        public Nullable<int> UserIdForSecondScale { get; set; }
        public bool Done { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual InvoiceTypes InvoiceTypes { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
