//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TowzinSaravan.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTotal
    {
        public int Id { get; set; }
        public string InvoiceType { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string CustomerName { get; set; }
        public string ProductType { get; set; }
        public string CarNumber { get; set; }
        public string DriverName { get; set; }
        public Nullable<int> SourceFullWeight { get; set; }
        public Nullable<int> SourceEmptyWeight { get; set; }
        public Nullable<int> SourceNetWeight { get; set; }
        public int FullWeight { get; set; }
        public int EmptyWeight { get; set; }
        public int NetWeight { get; set; }
        public bool FirstScale { get; set; }
        public System.DateTime FirstScaleDate { get; set; }
        public Nullable<System.TimeSpan> FirstScaleTime { get; set; }
        public string UsernameForFirstScale { get; set; }
        public bool SecondScale { get; set; }
        public Nullable<System.DateTime> SecondScaleDate { get; set; }
        public Nullable<System.TimeSpan> SecondScaleTime { get; set; }
        public string UsernameForSecondScale { get; set; }
        public bool Done { get; set; }
    }
}
